ERROR - 2024-06-06 02:37:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#4 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#5 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-06-06 02:37:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:37:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#5 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#6 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#7 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#4 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-06-06 02:37:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
 4 APPPATH/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:37:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#4 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#5 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-06-06 02:37:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:37:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#5 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#6 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#7 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#4 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-06-06 02:37:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
 4 APPPATH/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:37:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#4 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#5 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-06-06 02:37:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:37:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#5 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#6 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#7 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#4 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-06-06 02:37:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
 4 APPPATH/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:37:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#4 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#5 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-06-06 02:37:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:37:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#5 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#6 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#7 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#4 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-06-06 02:37:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
 4 APPPATH/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:38:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#5 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#6 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#7 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
#4 /var/www/html/app/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-06-06 02:38:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/lugarturistico_model.php(17): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Models/lugarturistico_model.php(62): App\Models\lugarturistico_model->execQuery()
 4 APPPATH/Controllers/LugarTuristico.php(76): App\Models\lugarturistico_model->getListadoGrid()
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\LugarTuristico->viewLugarTuristicoGrid()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-06 02:38:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u787956442_gad'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#5 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#6 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/app/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
#4 /var/www/html/system/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
#5 /var/www/html/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /var/www/html/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-06-06 02:38:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/categoria_model.php(23): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Categoria.php(46): App\Models\categoria_model->getListado()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Categoria->getjson_ListadoCategorias()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
